(library (http-pixiu core mime)
  (export guess-mime-type)
  (import (chezscheme))

  (define mime-hashtable
    (let ([ht (make-hashtable string-hash string=?)])
      (for-each
        (lambda (p)
          (hashtable-set! ht (car p) (cdr p)))
        '(("html"  . "text/html")
          ("htm"   . "text/html")
          ("css"   . "text/css")
          ("js"    . "application/javascript")
          ("mjs"   . "application/javascript")
          ("json"  . "application/json")
          ("png"   . "image/png")
          ("apng"  . "image/apng")
          ("jpg"   . "image/jpeg")
          ("jpeg"  . "image/jpeg")
          ("gif"   . "image/gif")
          ("webp"  . "image/webp")
          ("avif"  . "image/avif")
          ("svg"   . "image/svg+xml")
          ("ico"   . "image/x-icon")
          ("txt"   . "text/plain")
          ("md"    . "text/markdown")
          ("csv"   . "text/csv")
          ("xml"   . "application/xml")
          ("yaml"  . "application/yaml")
          ("yml"   . "application/yaml")
          ("pdf"   . "application/pdf")
          ("woff"  . "font/woff")
          ("woff2" . "font/woff2")
          ("ttf"   . "font/ttf")
          ("otf"   . "font/otf")
          ("eot"   . "application/vnd.ms-fontobject")
          ("wasm"  . "application/wasm")
          ("mp4"   . "video/mp4")
          ("webm"  . "video/webm")
          ("ogv"   . "video/ogg")
          ("mp3"   . "audio/mpeg")
          ("ogg"   . "audio/ogg")
          ("oga"   . "audio/ogg")
          ("opus"  . "audio/opus")
          ("weba"  . "audio/webm")
          ("zip"   . "application/zip")
          ("gz"    . "application/gzip")
          ("tar"   . "application/x-tar")
          ("7z"    . "application/x-7z-compressed")
          ("rar"   . "application/vnd.rar")))
      ht))

  (define (file-extension path)
    (let ([len (string-length path)])
      (let loop ([i (- len 1)])
        (cond
          [(< i 0) ""]
          [(char=? (string-ref path i) #\.)
           (substring path (+ i 1) len)]
          [else (loop (- i 1))]))))

  (define (guess-mime-type path)
    (let ([ext (string-downcase (file-extension path))])
      (or (hashtable-ref mime-hashtable ext #f)
          "application/octet-stream")))
)
