(library (http-pixiu core util form)
  (export parse-form-urlencoded)
  (import (chezscheme)
          (chibi uri)
          (only (srfi :13) string-trim-both))

  (define (string-split str delim)
    (let loop ([i 0] [start 0] [result '()])
      (if (>= i (string-length str))
          (reverse (cons (substring str start i) result))
          (if (char=? (string-ref str i) delim)
              (loop (+ i 1) (+ i 1) (cons (substring str start i) result))
              (loop (+ i 1) start result)))))

  (define (parse-form-urlencoded s)
    (let ([pairs (string-split (string-trim-both s) #\&)])
      (map (lambda (pair)
             (let ([kv (string-split pair #\=)])
               (cons (uri-decode (car kv))
                     (if (null? (cdr kv))
                         ""
                         (uri-decode (cadr kv))))))
           pairs)))
)
