(library (http-pixiu core util multipart)
  (export parse-multipart-form-data)
  (import (chezscheme))

  (define (string-trim-both s)
    (let ([len (string-length s)])
      (let loop-start ([i 0])
        (if (and (< i len) (char-whitespace? (string-ref s i)))
            (loop-start (+ i 1))
            (let loop-end ([j len])
              (if (and (> j i) (char-whitespace? (string-ref s (- j 1))))
                  (loop-end (- j 1))
                  (substring s i j)))))))

  (define (string-split str delim)
    (let loop ([i 0] [start 0] [result '()])
      (if (>= i (string-length str))
          (reverse (cons (substring str start i) result))
          (if (char=? (string-ref str i) delim)
              (loop (+ i 1) (+ i 1) (cons (substring str start i) result))
              (loop (+ i 1) start result)))))

  (define (string-index str ch)
    (let loop ([i 0])
      (cond
        [(>= i (string-length str)) #f]
        [(char=? (string-ref str i) ch) i]
        [else (loop (+ i 1))])))

  (define (find-boundary content-type)
    (let ([prefix "boundary="])
      (let loop ([i 0])
        (if (> (+ i (string-length prefix)) (string-length content-type))
            #f
            (if (equal? (substring content-type i (+ i (string-length prefix))) prefix)
                (string-trim-both (substring content-type (+ i (string-length prefix)) (string-length content-type)))
                (loop (+ i 1)))))))

  (define (parse-content-disposition value)
    (let ([parts (string-split value #\;)])
      (let loop ([ps parts] [result '()])
        (if (null? ps)
            result
            (let* ([trimmed (string-trim-both (car ps))]
                   [kv (string-split trimmed #\=)])
              (if (= (length kv) 2)
                  (let ([k (string-trim-both (car kv))]
                        [v (string-trim-both (cadr kv))])
                    (if (and (> (string-length v) 1)
                             (char=? (string-ref v 0) #\")
                             (char=? (string-ref v (- (string-length v) 1)) #\"))
                        (loop (cdr ps) (cons (cons k (substring v 1 (- (string-length v) 1))) result))
                        (loop (cdr ps) (cons (cons k v) result))))
                  (loop (cdr ps) result)))))))

  (define (bv-index-of bv needle start)
    (let ([n-len (bytevector-length needle)]
          [b-len (bytevector-length bv)])
      (let loop ([i start])
        (if (> (+ i n-len) b-len)
            #f
            (let check ([j 0])
              (if (>= j n-len)
                  i
                  (if (= (bytevector-u8-ref bv (+ i j)) (bytevector-u8-ref needle j))
                      (check (+ j 1))
                      (loop (+ i 1)))))))))

  (define (bv-prefix? bv start needle)
    (let ([n-len (bytevector-length needle)])
      (let loop ([i 0])
        (if (>= i n-len)
            #t
            (if (= (bytevector-u8-ref bv (+ start i)) (bytevector-u8-ref needle i))
                (loop (+ i 1))
                #f)))))

  (define (bv-find-crlf2 bv start)
    (let ([len (bytevector-length bv)])
      (let loop ([i start])
        (if (>= (+ i 3) len)
            #f
            (if (and (= (bytevector-u8-ref bv i) (char->integer #\return))
                     (= (bytevector-u8-ref bv (+ i 1)) (char->integer #\newline))
                     (= (bytevector-u8-ref bv (+ i 2)) (char->integer #\return))
                     (= (bytevector-u8-ref bv (+ i 3)) (char->integer #\newline)))
                i
                (loop (+ i 1)))))))

  (define (parse-multipart-form-data body-port content-type max-size)
    (let ([boundary (find-boundary content-type)])
      (if (not boundary)
          '()
          (let ([body-bv (guard (ex [#t #f]) (get-bytevector-all body-port))])
            (if (or (not body-bv)
                    (and max-size (> (bytevector-length body-bv) max-size)))
                '()
                (parse-multipart-bv body-bv boundary))))))

  (define (parse-multipart-bv bv boundary)
    (let ([delim (string->utf8 (string-append "--" boundary))]
          [end-delim (string->utf8 (string-append "--" boundary "--"))])
      (let loop ([pos 0] [parts '()])
        (let ([delim-pos (bv-index-of bv delim pos)])
          (if (not delim-pos)
              (reverse parts)
              (let ([after-delim (+ delim-pos (bytevector-length delim))])
                (if (and (<= (+ after-delim (bytevector-length end-delim)) (bytevector-length bv))
                         (bv-prefix? bv after-delim end-delim))
                    (reverse parts)
                    (let ([data-start (if (and (< (+ after-delim 1) (bytevector-length bv))
                                               (= (bytevector-u8-ref bv after-delim) (char->integer #\return))
                                               (= (bytevector-u8-ref bv (+ after-delim 1)) (char->integer #\newline)))
                                          (+ after-delim 2)
                                          after-delim)])
                      (let ([next-delim (bv-index-of bv delim data-start)])
                        (if (not next-delim)
                            (reverse parts)
                            (let ([part-len (max 0 (- next-delim data-start 2))])
                              (let ([part-bv (make-bytevector part-len)])
                                (bytevector-copy! bv data-start part-bv 0 part-len)
                                (loop next-delim (cons (parse-part part-bv) parts))))))))))))))

  (define (parse-part bv)
    (let ([sep (bv-find-crlf2 bv 0)])
      (if (not sep)
          `((name . #f) (filename . #f) (body . ,bv))
          (let ([header-bv (make-bytevector sep)])
            (bytevector-copy! bv 0 header-bv 0 sep)
            (let ([header-str (utf8->string header-bv)])
              (let ([header-lines (string-split header-str #\newline)])
                (let ([parsed-headers
                       (map (lambda (line)
                              (let ([trimmed (string-trim-both line)])
                                (let ([colon (string-index trimmed #\:)])
                                  (if colon
                                      (cons (string-downcase (string-trim-both (substring trimmed 0 colon)))
                                            (string-trim-both (substring trimmed (+ colon 1) (string-length trimmed))))
                                      (cons trimmed "")))))
                            header-lines)])
                  (let ([name #f] [filename #f])
                    (let ([cd (assoc "content-disposition" parsed-headers)])
                      (when cd
                        (let ([disp (parse-content-disposition (cdr cd))])
                          (set! name (cdr (assoc "name" disp)))
                          (let ([fn (assoc "filename" disp)])
                            (when fn (set! filename (cdr fn)))))))
                    (let ([body-len (- (bytevector-length bv) sep 4)])
                      (let ([body-bv (if (> body-len 0)
                                         (let ([p (make-bytevector body-len)])
                                           (bytevector-copy! bv (+ sep 4) p 0 body-len)
                                           p)
                                         (make-bytevector 0))])
                        `((name . ,name)
                          (filename . ,filename)
                          (headers . ,parsed-headers)
                          (body . ,body-bv))))))))))))
)
